stages:
  - pre_check
  - build

# Global variables
variables:
  ESP_IDF_TAG_LATEST: "latest"
  APP_NAME: "openocd-on-esp32"

.add_gitlab_key: &add_gitlab_key |
  command -v ssh-agent >/dev/null || exit 1
  eval $(ssh-agent -s)
  printf '%s\n' "${GITLAB_KEY}" | tr -d '\r' | ssh-add - > /dev/null
  mkdir -p ~/.ssh && chmod 700 ~/.ssh
  [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config || true

.submodules_mirror_update: &submodules_mirror_update |
  # Gitlab doesn't clean submodule contents
  git submodule foreach "git clean -d -x -f" || true
  # Use local mirror for submodules
  git config submodule.components/jimtcl/jimtcl.url https://gitlab-ci-token:${BOT_TOKEN}@${CI_SERVER_HOST}:${CI_SERVER_PORT}/idf/jimtcl.git
  git config submodule.main/openocd.url https://gitlab-ci-token:${BOT_TOKEN}@${CI_SERVER_HOST}:${CI_SERVER_PORT}/idf/openocd-esp32.git
  git submodule update --init

.build_template:
  stage: build
  variables:
    CHIP_NAME: "esp32s3"
  script:
    - *add_gitlab_key
    - *submodules_mirror_update
    - IDF_TARGET=${CHIP_NAME} idf.py build
    - cd build
    - esptool.py --chip ${CHIP_NAME} merge_bin -o ${APP_NAME}_merged.bin @flash_args

  artifacts:
    paths:
      - build/flasher_args.json
      - build/${APP_NAME}.elf
      - build/${APP_NAME}.bin
      - build/bootloader/bootloader.bin
      - build/bootloader/bootloader.elf
      - build/partition_table/partition-table.bin
      - build/${APP_NAME}_merged.bin
    expire_in: 2 weeks

build_latest:
  extends: .build_template
  image: espressif/idf:$ESP_IDF_TAG_LATEST
  tags:
    - build
  needs:
    - job: pre_commit

pre_commit:
  stage: pre_check
  image: espressif/idf:$ESP_IDF_TAG_LATEST
  script:
    - pip install pre-commit
    - git diff-tree --no-commit-id --name-only -r $CI_MERGE_REQUEST_TARGET_BRANCH_NAME -r $CI_COMMIT_SHA | xargs pre-commit run --files
